[package]
name = "daemon"
version.workspace = true
edition.workspace = true

[dependencies]
credential-manager = { path = "../credential-manager" }
policy = { path = "../policy" }
adapter-ssh = { path = "../adapter-ssh" }
adapter-totp = { path = "../adapter-totp" }
adapter-github = { path = "../adapter-github" }
